name: Docker Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          # Build the image and tag it locally as 'attendance-app'
          docker build -t attendance-app . 
          
      - name: Run Test (Headless)
        run: |
          # Use offscreen platform so it doesn't look for a monitor on the GitHub server
          docker run -e QT_QPA_PLATFORM=offscreen attendance-app